version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    allow:
      - dependency-type: "development"
    versioning-strategy: lockfile-only
    schedule:
      interval: "monthly"
    reviewers:
      - "Soulou"
