language: ruby

dist: trusty
sudo: false

cache: bundler

rvm:
  - 2.3.3

env:
  matrix:
    - "NSQ=nsq-1.0.0-compat.linux-amd64.go1.8"
    - "NSQ=nsq-0.3.8.linux-amd64.go1.6.2"

before_install:
  - wget https://s3.amazonaws.com/bitly-downloads/nsq/$NSQ.tar.gz -O /tmp/nsq.tar.gz
  - tar -xvf /tmp/nsq.tar.gz
  - export PATH=$PATH:$PWD/$NSQ/bin/

script:
  - bundle exec rake spec
